### PR TITLE
Only rebuild source when not up-to-date

### PR DESCRIPTION
**Pull request by mrkrstphr**
This will make deploying to multiple environments in a row faster

```
npm run deploy-staging -- --cache
```

### CODE REVIEW

**Comment by boboudreau** [comment]
Good idea. I haven't looked into it/tested it yet, though.

**Comment by mrkrstphr** [comment]
I've been using the shit out of this locally. It's super tight. Can I get a merge, please?

**Comment by mrkrstphr** [comment]
This maybe has a slight flaw when trying to deploy something to update a dependency: it won't work. Maybe need to do an `npm update` here?

**Comment by austinsmorris** [comment]
so it is super tight or flawed?

**Comment by mrkrstphr** [comment]
I'm going to add a `--cache` flag that triggers this behavior so that the developer has to opt in. Which hopefully means they know what they're doing.

**Comment by mrkrstphr** [comment]
This is ready to be pulled now.

**Comment by austinsmorris** [comment]
do we have a readme than can be documented in?

**Pull request merged**
